### TESTE DE ROTAS DE LOGIN E REGISTRO

@baseUrl = http://localhost:3000
@contentType = application/json

### LOGIN
# Consulta login
GET {{baseUrl}}/login
Content-Type: {{contentType}}

### REGISTRO
# Cria um novo usuário
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "email": "jonas.jonas@example.com",
  "password": "123456"
}



### ATUALIZAR USUÁRIO
# Atualiza os dados de um usuário existente
PUT {{baseUrl}}/login/4
Content-Type: {{contentType}}

{
  "email": "jonas.jonas@example.com",
  "password": "voceegay"
}

########TASKS#########

###CONSULTAR TASKS POR ID
GET {{baseUrl}}/tasks?user_id=1
Content-Type: {{contentType}}


###CADASTRAR TASKS
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}

{
    "user_id": "1",
    "name": "Nova Tarefa Teste",
    "priority": "Média",
    "status": "Concluído",
    "completed_at": ""
}

###ALTERAR DADOS DA TASKS
PUT {{baseUrl}}/tasks/2
Content-Type: {{contentType}}

{
    "user_id": "1",
    "name": "Alteração",
    "priority": "Alta",
    "status": "Reaberto",
    "created_at": "2025-11-14T03:10:53.555Z",
    "completed_at": ""
}


###DELETAR TASKS

DELETE {{baseUrl}}/tasks/11
Content-Type: {{contentType}}

{

    "user_id": "1"
}






