### TESTE DE ROTAS DE LOGIN E REGISTRO

@baseUrl = http://localhost:3000
@contentType = application/json

### LOGIN
# Realiza o login do usuário
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "jonas@jonas.com",
  "pass": "123456"
}

### REGISTRO
# Cria um novo usuário
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "user_id": "2",
  "email": "jonas@jonera.com",
  "pass": "123456"
}



### ATUALIZAR USUÁRIO
# Atualiza os dados de um usuário existente
PUT {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "email": "jonas@joner.com",
  "pass": "ovaSenhoee"
}

########TASKS#########

###CADASTRAR TASKS
POST {{baseUrl}}/user/1/tasks
Content-Type: {{contentType}}

{
  
  "task_id": "1",
  "title": "Teste",
  "description": "Teste",
  "status": "andamento"
}

###ALTERAR DADOS DA TASKS
PUT {{baseUrl}}/tasks
Content-Type: {{contentType}}

{
  "id": "3",
  "title": "Teste1",
  "description": "Teste2",
  "status": "CONCLUÍDO"
}

###CONSULTAR TASKS ESPECIFICAS

GET {{baseUrl}}/user/2/tasks/1
Content-Type: {{contentType}}

{
}


###DELETAR TASKS

DELETE {{baseUrl}}/tasks/3
Content-Type: {{contentType}}





