### TESTE DE ROTAS DE LOGIN E REGISTRO

@baseUrl = http://localhost:3000
@contentType = application/json

### LOGIN
# Realiza o login do usuário
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
  "email": "jonas@jonas.com",
  "pass": "123456"
}

### REGISTRO
# Cria um novo usuário
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "email": "jonas@joner.com",
  "pass": "123456"
}



### ATUALIZAR USUÁRIO
# Atualiza os dados de um usuário existente
PUT {{baseUrl}}/register
Content-Type: {{contentType}}

{
  "email": "jonas@joner.com",
  "pass": "ovaSenhoee"
}

###CADASTRAR TASK
POST {{baseUrl}}/task
Content-Type: {{contentType}}

{
  "id": "1",
  "title": "Teste",
  "description": "Teste",
  "status": "andamento"
}

###ALTERAR DADOS DA TASK
PUT {{baseUrl}}/task
Content-Type: {{contentType}}

{
  "id": "3",
  "title": "Teste1",
  "description": "Teste2",
  "status": "CONCLUÍDO"
}

###DELETAR TASKS

DELETE {{baseUrl}}/task/3
Content-Type: {{contentType}}





